### ISSUE TITLE
Mongoose Long typescript - I cannot figure out how to do it.

### ISSUE THREAD

**Issue by spydmobile** [mongoosejs/mongoose-long#13]
Hi, New to this plugin, trying to implement it in typescript, not finding the types. 
Hoping for a little direction, thanks in advance.

![Screen Shot 2021-01-05 at 5 08 16 PM](https://user-images.githubusercontent.com/1065978/103713128-cb468b80-4f78-11eb-8864-dc7867a236b8.png)

**Comment by vkarpov15** [comment]
We don't have TypeScript bindings for this project yet. Will look into this for the future.

**Comment by JeanPoffo** [comment]
Hi @spydmobile !

A simple solution for this is create a DTS files and put the new type:

![carbon](https://user-images.githubusercontent.com/18728222/109955642-7c3f7d00-7cc1-11eb-948c-d93e06960605.png)

**Comment by JeanPoffo** [comment]
Hi @spydmobile !

To resolve this problem, simple create a new DTS file, to Module Augmentation.

![carbon (1)](https://user-images.githubusercontent.com/18728222/109993384-fe906700-7cea-11eb-862b-7533460f4540.png)
