### ISSUE TITLE
[Typescript] TypeError: mongooseLong.default is not a function

### ISSUE THREAD

**Issue by Jovidon** [mongoosejs/mongoose-long#15]
First usage: 
```
import * as mongoose from 'mongoose';
import * as mongooseLong  from 'mongoose-long';
mongooseLong.default(mongoose);
```
Second usage:
```
import * as mongoose from 'mongoose';
import mongooseLong from 'mongoose-long';
mongooseLong(mongoose);
```

On both usages gives following error after build :
```

mongooseLong.default(mongoose);
                    ^
TypeError: mongooseLong.default is not a function
```

Build file:
```const mongoose = require("mongoose");
const mongoose_long_1 = require("mongoose-long");
mongoose_long_1.default(mongoose);
```

**Comment by vkarpov15** [comment]
Can you please provide your TS config?

**Comment by Jovidon** [comment]
tsconfig.json :
`{
  "compilerOptions": {
    "noImplicitAny": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "outDir": "build",
    "module": "commonjs",
    "target": "ES2019",
    "declaration": false,
    "baseUrl": "node_modules"
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.spec.ts", "**/*.test.ts", "test"]
}
`

**Comment by vkarpov15** [comment]
Expected behavior unfortunately. You need to enable `allowSyntheticDefaultImports` and `esModuleInterop` in your `tsconfig.json`.

```
{
  "compilerOptions": {
    "noImplicitAny": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "outDir": "build",
    "module": "commonjs",
    "target": "ES2019",
    "declaration": false,
    "baseUrl": "node_modules",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.spec.ts", "**/*.test.ts", "test"]
}
```

**Comment by Jovidon** [comment]
> Expected behavior unfortunately. You need to enable `allowSyntheticDefaultImports` and `esModuleInterop` in your `tsconfig.json`.
> 
> ```
> {
>   "compilerOptions": {
>     "noImplicitAny": false,
>     "removeComments": true,
>     "emitDecoratorMetadata": true,
>     "experimentalDecorators": true,
>     "outDir": "build",
>     "module": "commonjs",
>     "target": "ES2019",
>     "declaration": false,
>     "baseUrl": "node_modules",
>     "allowSyntheticDefaultImports": true,
>     "esModuleInterop": true
>   },
>   "include": ["src/**/*"],
>   "exclude": ["node_modules", "**/*.spec.ts", "**/*.test.ts", "test"]
> }
> ```

Thank you.
