### ISSUE TITLE
Use back as a number

### ISSUE THREAD

**Issue by vschoener** [mongoosejs/mongoose-long#7]
I just try this package and it works, I got my number properly store instead having a weird Double.

But now, I try to use back and I don't really know how to do it. I thought I could use it normally but when I compare the value, for example, it says it's an object: { Object (_bsontype, low_, ...) }

Example:

`const id: mongoose.SchemaTypes.Long = 10;
 // Failed
 if (id == 10) {...}
`

Any idea or suggestion ?

**Comment by vkarpov15** [comment]
Use id.toNumber() .

**Comment by vschoener** [comment]
Thank you
