### ISSUE TITLE
Bundle with mongoose proper

### ISSUE THREAD

**Issue by ceefour** [mongoosejs/mongoose-long#8]
I'm not really sure why mongoose-long, mongoose-int32, etc. has to be in their own npm packages.

These types are built-in supported MongoDB types, so people expect to be able to use them with mongoose without additional extra step.

It'd be great if this project can be bundled within mongoose.

**Comment by vkarpov15** [comment]
They are built-in MongoDB types, but they don't necessarily map well to JavaScript types. Even [BigInt](http://thecodebarbarian.com/an-overview-of-bigint-in-node-js) doesn't quite line up with what a long is in MongoDB, so if you store something as an `int32` in MongoDB it would still look like a Number in JavaScript.
